ARG BALENA_MACHINE_NAME_ARG=%%BALENA_MACHINE_NAME%%

FROM balenalib/$BALENA_MACHINE_NAME_ARG-debian:run

RUN curl -fsSL https://pkgs.tailscale.com/stable/raspbian/buster.gpg | sudo apt-key add -
RUN curl -fsSL https://pkgs.tailscale.com/stable/raspbian/buster.list | sudo tee /etc/apt/sources.list.d/tailscale.list

RUN install_packages iptables tailscale

COPY init.sh /init.sh
RUN chmod +x /init.sh

ENTRYPOINT ["/init.sh"]